# Generated by Django 3.2.3 on 2021-05-29 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_photo_albom'),
    ]

    operations = [
        migrations.AddField(
            model_name='albom',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albom', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.albom')),
                ('photo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.photo')),
            ],
        ),
    ]
