# Generated by Django 3.2.3 on 2021-05-29 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20210529_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='albom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.albom'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.photo'),
        ),
    ]
