# Generated by Django 3.2.3 on 2021-05-29 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20210529_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='albom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.albom'),
        ),
    ]
